POST http://localhost:8080/api/assistant/ask
Content-Type: application/json

{
  "question": "Qual trilha combina com uma caminhada curta?"
}

### Tool calling
# @timeout 2 m
POST http://localhost:8080/api/assistant/ask
Content-Type: application/json

{
  "question": "Quais trilhas fáceis existem no Rio de Janeiro?"
}

### Tool calling
# @timeout 2 m
POST http://localhost:8080/api/assistant/ask
Content-Type: application/json

{
  "question": "Quais trilhas difíceis existem no Rio de Janeiro?"
}

### indexar
POST http://localhost:8080/api/assistant/index


### RAG: trilha com guia indexado
# @timeout 2 m
POST http://localhost:8080/api/assistant/ask
Content-Type: application/json

{
  "question": "Têm algum interesse arqueológico na Pedra da Gávea?"
}

### RAG: trilha sem guia indexado
# @timeout 2 m
POST http://localhost:8080/api/assistant/ask
Content-Type: application/json

{
  "question": "A trilha do Caminho da Lagartixa tem trecho exposto?"
}