server:
  port: 8081
spring:
  application:
    name: inventory-mcp-server
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: inventory-mcp-server
        version: 1.0.0
        type: SYNC