spring:
  application:
    name: tasks
app:
  security:
    jwt-secret: ${JWT_SECRET:dev-secret-com-pelo-menos-32-caracteres}
    users:
      - username: user
        password: $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
        roles:
          - USER
      - username: admin
        password: $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
        roles:
          - ADMIN